use anthropic_sdk::{Client, MessageParam, TextBlock};
use std::io::Write;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::builder().build()?;
    
    let prompt = r#"
    Create a Rust implementation of a Binary Search Tree (BST) data structure with the following:
    1. A Node struct that holds an integer value and references to left and right children
    2. A BinarySearchTree struct with methods for:
       - insert(value): Insert a value into the BST
       - search(value): Find a value in the BST
       - inorder_traversal(): Get all values in sorted order
       - delete(value): Remove a value from the BST
    3. Include detailed comments explaining the logic
    4. Include a main function demonstrating usage of all operations
    
    Please provide only the Rust code without any markdown formatting or additional text.
    "#;

    println!("Generating Binary Search Tree implementation using Claude API...\n");
    
    let mut output = String::new();
    
    let mut stream = client
        .messages()
        .stream(
            vec![MessageParam::User {
                content: prompt.to_string(),
            }],
            "claude-3-5-sonnet-20241022".to_string(),
        )
        .await?;

    while let Some(event) = stream.next().await {
        match event {
            Ok(event) => {
                if let Some(content_block_delta) = event.delta.as_ref().and_then(|d| d.delta.as_ref()) {
                    if let Some(text_delta) = content_block_delta.as_any().downcast_ref::<serde_json::Value>() {
                        if let Some(text) = text_delta.get("text").and_then(|t| t.as_str()) {
                            output.push_str(text);
                            print!("{}", text);
                            std::io::stdout().flush()?;
                        }
                    }
                }
            }
            Err(e) => {
                eprintln!("Error in stream: {}", e);
            }
        }
    }

    println!("\n\n--- Generated Code Above ---\n");
    
    // Extract the code and compile it
    if let Some(start) = output.find("fn main()") {
        let code = &output[start..];
        if let Some(end) = code.rfind('}') {
            let complete_code = format!(
                r#"
// Binary Search Tree implementation generated by Claude

use std::cmp::Ordering;

{}
"#,
                &code[..=end]
            );

            println!("Attempting to compile and run the generated code...\n");

            // Write to a temporary file and compile
            let temp_file = "/tmp/bst_generated.rs";
            std::fs::write(temp_file, complete_code)?;

            let output = std::process::Command::new("rustc")
                .arg(temp_file)
                .arg("-o")
                .arg("/tmp/bst_generated")
                .output()?;

            if output.status.success() {